escribir_cadena ('Introduce un número: ');
leer (n1);
escribir_cadena ('Introduce otro número: ');
leer (n2);
escribir (n1);
escribir_cadena ('/');
escribir (n2);
escribir_cadena (' = ');
escribir (n1/n2);
escribir_cadena ('\nEl cociente de la división = ');
escribir (n1 _div n2);
escribir_cadena (' y el resto ');
escribir (n1 _mod n2);
escribir_cadena ('\n');
