#define inicio            257
#define fin               258
#define leer              259
#define escribir          260
#define si                261
#define entonces          262
#define si_no             263
#define fin_si            264
#define mientras          265
#define hacer             266
#define fin_mientras      267
#define repetir           268
#define hasta_que         269
#define para              270
#define desde             271
#define hasta             272
#define paso              273
#define fin_para          274
#define identifier        275
#define number            276
#define string            277
#define assignment        278
#define sum               279
#define subtraction       280
#define product           281
#define division          282
#define __mod             283
#define power             284
#define concatenation     285
#define less_than         286
#define less_equal_than   287
#define more_than         288
#define more_equal_than   289
#define equal             290
#define not_equal         291
#define __o               292
#define __y               293
#define __no              294
#define comments          295
#define comment           296
#define sentence_end      297
#define open_parenthesis  298
#define close_parenthesis 299
