/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internationalization;

import java.awt.Component;
import java.text.DecimalFormat;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author victor
 */
public class Internationalization extends javax.swing.JFrame {

    /**
     * Creates new form Internationalization
     */
    public Internationalization() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _panel = new java.awt.Panel();
        _english = new javax.swing.JLabel();
        _spanish = new javax.swing.JLabel();
        _quantity = new javax.swing.JLabel();
        _textField = new javax.swing.JTextField();
        _backCurrency = new javax.swing.JLabel();
        _deleteButton = new javax.swing.JButton();
        _frontCurrency = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);

        _panel.setBackground(java.awt.Color.darkGray);

        _english.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/united_kingdom.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("internationalization/Bundle"); // NOI18N
        _english.setText(bundle.getString("Internationalization._english.text")); // NOI18N
        _english.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                english(evt);
            }
        });

        _spanish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/spain.png"))); // NOI18N
        _spanish.setText(bundle.getString("Internationalization._spanish.text")); // NOI18N
        _spanish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spanish(evt);
            }
        });

        _quantity.setFont(new java.awt.Font("Droid Sans", 1, 15)); // NOI18N
        _quantity.setForeground(java.awt.Color.lightGray);
        _quantity.setText(bundle.getString("Internationalization._quantity.text")); // NOI18N

        _textField.setBackground(java.awt.Color.darkGray);
        _textField.setFont(new java.awt.Font("Droid Sans Mono", 1, 15)); // NOI18N
        _textField.setForeground(java.awt.Color.white);
        _textField.setText(bundle.getString("Internationalization._textField.text")); // NOI18N
        _textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                write(evt);
            }
        });

        _backCurrency.setFont(new java.awt.Font("Droid Sans Mono", 0, 15)); // NOI18N
        _backCurrency.setForeground(java.awt.Color.darkGray);
        _backCurrency.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _backCurrency.setText(bundle.getString("Internationalization._backCurrency.text")); // NOI18N

        _deleteButton.setBackground(java.awt.Color.darkGray);
        _deleteButton.setFont(new java.awt.Font("Droid Sans", 0, 15)); // NOI18N
        _deleteButton.setForeground(java.awt.Color.white);
        _deleteButton.setText(bundle.getString("Internationalization._deleteButton.text")); // NOI18N
        _deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete(evt);
            }
        });

        _frontCurrency.setFont(new java.awt.Font("Droid Sans Mono", 0, 15)); // NOI18N
        _frontCurrency.setForeground(java.awt.Color.darkGray);
        _frontCurrency.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _frontCurrency.setText(bundle.getString("Internationalization._frontCurrency.text")); // NOI18N

        javax.swing.GroupLayout _panelLayout = new javax.swing.GroupLayout(_panel);
        _panel.setLayout(_panelLayout);
        _panelLayout.setHorizontalGroup(
            _panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_frontCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_panelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(_backCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(_panelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(_panelLayout.createSequentialGroup()
                                .addComponent(_english)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_spanish)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        _panelLayout.setVerticalGroup(
            _panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_english)
                    .addComponent(_spanish))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_frontCurrency)
                    .addComponent(_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_quantity)
                    .addComponent(_backCurrency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_deleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void translate() {
        Internationalization in = new Internationalization();
              
        Component[] components = _panel.getComponents();
        for(int i = 0; i < components.length; i++) {
            String name = in._panel.getComponent(i).getAccessibleContext().getAccessibleName();
            if(components[i] instanceof JLabel) {
                JLabel component = (JLabel) _panel.getComponent(i);
                component.setText(name);
            }
            else if(components[i] instanceof JButton) {
                JButton component = (JButton) _panel.getComponent(i);
                component.setText(name);
            }
        }
    }
    
    private void spanish(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spanish
        if(!"es".equals(Locale.getDefault().getLanguage())) {
            Locale.setDefault(new Locale("es", "ES"));
            _textField.setHorizontalAlignment(JTextField.RIGHT);
            if(!_textField.getText().isEmpty()) {
                String aux = _textField.getText();
                aux = aux.replace(",", "");
                double quantity = Double.parseDouble(aux);
                DecimalFormat format;
                if(aux.contains(".")) {
                    if(aux.charAt(aux.length()-1) == '0' &&
                       aux.charAt(aux.length()-2) == '.') {
                        format = new DecimalFormat("#,###");
                    } else if(aux.charAt(aux.length()-2) == '.') {
                        format = new DecimalFormat("#,###.0");
                    }else if(aux.charAt(aux.length()-1) == '.') {
                        format = new DecimalFormat("#,###");
                    }else if(aux.charAt(aux.length()-1) == '0') {
                        format = new DecimalFormat("#,###.0");
                    } else {
                        format = new DecimalFormat("#,###.00");
                    }
                } else {
                    format = new DecimalFormat("#,###");
                }
                _textField.setText(format.format(quantity));
                if(_textField.getText().charAt(0) == ','){
                    _textField.setText("0" + _textField.getText());
                }
            }
            translate();
        }
    }//GEN-LAST:event_spanish

    private void english(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_english
        if(!"en".equals(Locale.getDefault().getLanguage())) {
            Locale.setDefault(Locale.UK);
            _textField.setHorizontalAlignment(JTextField.LEFT);
            if(!_textField.getText().isEmpty()) {
                String aux = _textField.getText();
                aux = aux.replace(".", "");
                aux = aux.replace(",", ".");
                double quantity = Double.parseDouble(aux);
                DecimalFormat format;
                if(aux.contains(".")) {
                    if(aux.charAt(aux.length()-1) == '0' &&
                       aux.charAt(aux.length()-2) == '.') {
                        format = new DecimalFormat("#,###");
                    } else if(aux.charAt(aux.length()-2) == '.') {
                        format = new DecimalFormat("#,###.0");
                    }else if(aux.charAt(aux.length()-1) == '.') {
                        format = new DecimalFormat("#,###");
                    }else if(aux.charAt(aux.length()-1) == '0') {
                        format = new DecimalFormat("#,###.0");
                    } else {
                        format = new DecimalFormat("#,###.00");
                    }
                } else {
                    format = new DecimalFormat("#,###");
                }
                _textField.setText(format.format(quantity));
                if(_textField.getText().charAt(0) == '.'){
                    _textField.setText("0" + _textField.getText());
                }
            }
            translate();
        }
    }//GEN-LAST:event_english

    private void delete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete
        _textField.setText("");
    }//GEN-LAST:event_delete

    private void write(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_write
        char decimalSeparator;
        char separator;
        
        if(Locale.getDefault().getLanguage().equals("es")) {
            decimalSeparator = ',';
            separator = '.';
        } else {
            decimalSeparator = '.';
            separator = ',';
        }
        
        if(evt.getKeyChar() == decimalSeparator) {
            if(_textField.getText().contains(String.valueOf(decimalSeparator))) {
                evt.consume();
            } else if(_textField.getText().isEmpty()){
                evt.consume();
            }
        } else if(evt.getKeyChar() == '\b') {
            if(!_textField.getText().isEmpty()) {
                String aux = _textField.getText();
                aux = aux.replace(String.valueOf(separator), "");
                if(!aux.contains(String.valueOf(decimalSeparator))){
                    long quantity = Long.parseLong(aux);
                    DecimalFormat format = new DecimalFormat("#,###");
                    _textField.setText(format.format(quantity));
                }
            }
        } else if(evt.getKeyChar() < 48 || evt.getKeyChar() > 57) {
            evt.consume();
        } else {
            if(_textField.getText().contains(String.valueOf(decimalSeparator))) {
                if(_textField.getText().indexOf(decimalSeparator) < _textField.getText().length()-2) {
                    evt.consume();
                } else if(_textField.getText().charAt(_textField.getText().length()-1) == '0'
                       && evt.getKeyChar() == '0') {
                    evt.consume();
                }
            } else {
                String aux = _textField.getText();
                aux = aux.replace(String.valueOf(separator), "");
                aux = aux.concat(String.valueOf(evt.getKeyChar()));
                long quantity = Long.parseLong(aux);
                DecimalFormat format = new DecimalFormat("#,###");
                _textField.setText(format.format(quantity));
                evt.consume();
            }
        }
    }//GEN-LAST:event_write

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Internationalization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Internationalization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Internationalization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Internationalization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Internationalization().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _backCurrency;
    private javax.swing.JButton _deleteButton;
    private javax.swing.JLabel _english;
    private javax.swing.JLabel _frontCurrency;
    private java.awt.Panel _panel;
    private javax.swing.JLabel _quantity;
    private javax.swing.JLabel _spanish;
    private javax.swing.JTextField _textField;
    // End of variables declaration//GEN-END:variables
}
